### ISSUE TITLE
gutter on both sides would make it easier to work with borders

### ISSUE THREAD

**Issue by maoberlehner** [avalanchesass/avalanche_object_grid#10]
``` css
.o-grid {
  margin-right: -1em;
  margin-left: -1em;
}

.o-grid__item {
  padding-right: 0.5em;
  padding-left: 0.5em;
}
```
